# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Code quality

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      if: always()
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_development.txt
        pip install -r requirements.txt
    - name: Lint with pylint
      if: always()
      run: |
        pylint argostime
    - name: Check types with mypy
      if: always()
      run: |
        mypy --install-types --non-interactive --ignore-missing-imports argostime
#    - name: Test with unittest
#      run: |
#        python3 -m unittest argostime
